### ISSUE TITLE
Question about seg2su_clean

### ISSUE THREAD

**Issue by PhDSWseismics** [spasquet/SWIP#9]
Hello 

I use SWIP as a routine to analyse surface waves signals, and I usually have no problems from the extraction of dispersion to inversion of surface waves.

But now I have some issues with the last data i have to analyse : this set of data was extracted with an ABEM Terraloc system, and the files are in .SG2 format, instead of the .seg2 or .segy I usually have : seg2su_clean cannot find any file in the folder, here is the error message

>  No SEG2 or SEGY files in the selected folder

1. I converted the files in .sey or .seg2 with geopsy, I modified manually the headers with geopsy and here is the error message displayed : 

> Reading SEG2 files...
> seg2segy 2001.dat 33: Segmentation fault
> 
> susort: fgettr.c: bad first header
> 
>    Extract original acquisition settings from SEG2(Y) file(s)
> Attempted to access hdrs(:,1); index out of bounds because size(hdrs)=[0,0].
> Error in seg2su_clean (line 150)
> fldrall = hdrs(:,1); 
> 

2. I tried to resample the files, here is the result in SWIP console : 

Extract original acquisition settings from SEG2(Y) file(s)

> 
>    33 shot(s)
>    delay = -0.01 s
>    dt = 0.7 ms
>    ns = 2340
>    Record length = 1.638 s
> 
>    Original deployment settings
> In an assignment  A(I) = B, the number of elements in B and I must be the same.
> Error in seg2su_clean (line 217)
>         sx(i)=unique(sxall(fldrall==fldr(i))); 

Here is my configuration : 
Ubuntu 20.04 LTS
SWIP 2.2
Geopsy 3.1.0
SU : lastest version

How can I fix the problem ?

Thanks a lot

**Comment by spasquet** [comment]
Hi, sorry for the late reply, I don't know why but github did not send me a notification for your message.
You probably sorted this out already, but if I can help let me know.

My first guess would be to just rename the sg2 files in seg2. If it doesn't work, maybe you can send me your data and I can take a look at it.

Best
Sylvain
